"""empty message

Revision ID: 5ed476b81fd0
Revises: 
Create Date: 2017-05-21 09:10:39.730518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed476b81fd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=25), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('mb_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('mb_used', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('fext', sa.String(length=20), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_fext'), 'file', ['fext'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    op.create_index(op.f('ix_file_owner'), 'file', ['owner'], unique=False)
    op.create_index(op.f('ix_file_public_key'), 'file', ['public_key'], unique=False)
    op.create_index(op.f('ix_file_size'), 'file', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_size'), table_name='file')
    op.drop_index(op.f('ix_file_public_key'), table_name='file')
    op.drop_index(op.f('ix_file_owner'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_fext'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_table('user')
    op.drop_table('rank')
    # ### end Alembic commands ###
